#Requires -Version 5.1
<#
.SYNOPSIS
  Ensure shared documentation theme is available and merge into projectDocu.

.DESCRIPTION
  Resolves theme from (first hit wins):
    1. -ThemeSource / $env:THEME_SOURCE
    2. Repo .docu-builder-theme (with theme assets)
    3. Sibling ../docu-builder-theme (multi-root workspace)
    4. git clone of -ThemeRepository @ -ThemeRef (unless -SkipThemeFetch)

  Then merges theme + .winccoa-docu-builder into src/Squirt/data/projectDocu.
#>
[CmdletBinding()]
param(
    [string] $RepoRoot = "",
    [string] $WorkerPath = "src/Squirt",
    [string] $ThemePath = ".docu-builder-theme",
    [string] $ThemeRepository = "winccoa-tools-pack/docu-builder-theme",
    [string] $ThemeRef = "main",
    [string] $ThemeSource = "",
    [switch] $SkipThemeFetch,
    [string[]] $ProjectDocuPaths = @()
)

$ErrorActionPreference = "Stop"

if (-not $RepoRoot) {
    $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
}
if (-not $ThemeSource -and $env:THEME_SOURCE) {
    $ThemeSource = $env:THEME_SOURCE
}
if ($env:SKIP_THEME_FETCH -eq "1") {
    $SkipThemeFetch = $true
}

function Test-ThemeTree {
    param([string] $Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Container)) { return $false }
    return (Test-Path -LiteralPath (Join-Path $Path "extra_header.html")) -or
           (Test-Path -LiteralPath (Join-Path $Path "doxygen-awesome.css"))
}

function Copy-ThemeTopLevel {
    param([string] $From, [string] $To)
    New-Item -ItemType Directory -Force -Path $To | Out-Null
    $SkipThemeMeta = @('README.md', 'LICENSE', '.gitignore', '.gitattributes', '.editorconfig')
    Get-ChildItem -LiteralPath $From -File | ForEach-Object {
        if ($SkipThemeMeta -contains $_.Name) { return }
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $To $_.Name) -Force
    }
}

function Resolve-ThemeDir {
    $dest = Join-Path $RepoRoot $ThemePath

    if ($ThemeSource) {
        $candidate = $ThemeSource
        if (-not [System.IO.Path]::IsPathRooted($candidate)) {
            $candidate = Join-Path $RepoRoot $candidate
        }
        if (-not (Test-ThemeTree $candidate)) {
            throw "THEME_SOURCE is not a theme tree: $candidate"
        }
        Write-Host "Using local theme source: $candidate"
        Copy-ThemeTopLevel -From $candidate -To $dest
        Write-Host "Synced top-level theme files into: $dest"
        return $dest
    }

    if (Test-ThemeTree $dest) {
        Write-Host "Using existing theme at: $dest"
        return $dest
    }

    $sibling = Join-Path (Split-Path $RepoRoot -Parent) "docu-builder-theme"
    if (Test-ThemeTree $sibling) {
        Write-Host "Using local theme source: $sibling"
        Copy-ThemeTopLevel -From $sibling -To $dest
        Write-Host "Synced top-level theme files into: $dest"
        return $dest
    }

    if ($SkipThemeFetch) {
        throw "theme not found at $dest and -SkipThemeFetch was set"
    }

    $url = "https://github.com/$ThemeRepository.git"
    Write-Host "Fetching theme ${ThemeRepository}@${ThemeRef} -> $dest"
    if (Test-Path -LiteralPath (Join-Path $dest ".git")) {
        git -C $dest fetch --depth 1 origin $ThemeRef
        git -C $dest checkout -q FETCH_HEAD
    }
    else {
        if (Test-Path -LiteralPath $dest) {
            Remove-Item -LiteralPath $dest -Recurse -Force
        }
        git clone --depth 1 --branch $ThemeRef $url $dest
        if ($LASTEXITCODE -ne 0) {
            git clone --depth 1 $url $dest
            if ($ThemeRef -notin @("main", "master")) {
                git -C $dest checkout -q $ThemeRef
            }
        }
    }
    return $dest
}

$null = Resolve-ThemeDir

$sources = @()
if ($ProjectDocuPaths -and $ProjectDocuPaths.Count -gt 0) {
    $sources = $ProjectDocuPaths
}
elseif ($env:PROJECT_DOCU_PATHS) {
    $sources = @($env:PROJECT_DOCU_PATHS -split "[,\s;]+" | Where-Object { $_ })
}
else {
    $sources = @($ThemePath, ".winccoa-docu-builder")
}

Write-Host "Preparing projectDocu merge sources:"
$sources | ForEach-Object { Write-Host "  - $_" }

& (Join-Path $PSScriptRoot "merge-project-docu.ps1") -RepoRoot $RepoRoot -WorkerPath $WorkerPath @sources

$marker = Join-Path $RepoRoot (Join-Path $WorkerPath "data\projectDocu\.generated-by-docu-builder")
@(
    "# Generated by prepare-project-docu.ps1 - do not edit."
    "# Theme: ${ThemeRepository}@${ThemeRef}"
    "# Worker: $WorkerPath"
    "# UTC: $([DateTime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ'))"
) | Set-Content -LiteralPath $marker -Encoding utf8

Write-Host "projectDocu prepare complete."
