#!/usr/bin/env bash
# Ensure the shared documentation theme is available and merge it with
# project overrides into src/Squirt/data/projectDocu.
#
# Default sources (in order):
#   1. .docu-builder-theme   (checkout / sibling clone of docu-builder-theme)
#   2. .winccoa-docu-builder (this project's advanced config + overrides)
#
# Env:
#   REPO_ROOT            repository root (default: auto)
#   WORKER_PATH          worker project path (default: src/Squirt)
#   THEME_PATH           theme checkout path (default: .docu-builder-theme)
#   THEME_REPOSITORY     owner/name (default: winccoa-tools-pack/docu-builder-theme)
#   THEME_REF            git ref (default: main)
#   THEME_SOURCE         optional absolute/relative path to a local theme tree
#                        (sibling ../docu-builder-theme is tried automatically)
#   SKIP_THEME_FETCH=1   never clone/fetch; fail if theme dir is missing
#   PROJECT_DOCU_PATHS   optional extra/override list (newline/space/comma)
#                        When set, replaces the default theme+project list.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
WORKER_PATH="${WORKER_PATH:-src/Squirt}"
THEME_PATH="${THEME_PATH:-.docu-builder-theme}"
THEME_REPOSITORY="${THEME_REPOSITORY:-winccoa-tools-pack/docu-builder-theme}"
THEME_REF="${THEME_REF:-main}"
SKIP_THEME_FETCH="${SKIP_THEME_FETCH:-0}"

cd "${REPO_ROOT}"

resolve_theme_dir() {
  local candidate
  if [ -n "${THEME_SOURCE:-}" ]; then
    candidate="${THEME_SOURCE}"
    case "${candidate}" in
      /*) ;;
      *) candidate="${REPO_ROOT}/${candidate}" ;;
    esac
    if [ -d "${candidate}" ]; then
      echo "${candidate}"
      return 0
    fi
    echo "error: THEME_SOURCE does not exist: ${candidate}" >&2
    return 2
  fi

  candidate="${REPO_ROOT}/${THEME_PATH}"
  if { [ -d "${candidate}" ] && { [ -f "${candidate}/extra_header.html" ] || [ -f "${candidate}/doxygen-awesome.css" ]; }; }; then
    echo "${candidate}"
    return 0
  fi

  # Sibling checkout in a multi-root workspace (local dev).
  candidate="$(cd "${REPO_ROOT}/.." && pwd)/docu-builder-theme"
  if { [ -d "${candidate}" ] && { [ -f "${candidate}/extra_header.html" ] || [ -f "${candidate}/doxygen-awesome.css" ]; }; }; then
    echo "${candidate}"
    return 0
  fi

  return 1
}

ensure_theme() {
  local theme_dir
  if theme_dir="$(resolve_theme_dir)"; then
    # If resolve hit a sibling path, materialize/sync into THEME_PATH for CI parity.
    local dest="${REPO_ROOT}/${THEME_PATH}"
    if [ "${theme_dir}" != "${dest}" ]; then
      echo "Using local theme source: ${theme_dir}"
      mkdir -p "${dest}"
      # Copy top-level theme files only (merge semantics).
      find "${theme_dir}" -maxdepth 1 -type f ! -name 'README.md' ! -name 'LICENSE' ! -name '.gitignore' ! -name '.gitattributes' ! -name '.editorconfig' -exec cp -f {} "${dest}/" \;
      echo "Synced top-level theme files into: ${dest}"
      echo "${dest}"
      return 0
    fi
    echo "Using existing theme at: ${theme_dir}"
    echo "${theme_dir}"
    return 0
  fi

  if [ "${SKIP_THEME_FETCH}" = "1" ]; then
    echo "error: theme not found at ${REPO_ROOT}/${THEME_PATH} and SKIP_THEME_FETCH=1" >&2
    return 2
  fi

  local dest="${REPO_ROOT}/${THEME_PATH}"
  local url="https://github.com/${THEME_REPOSITORY}.git"
  echo "Fetching theme ${THEME_REPOSITORY}@${THEME_REF} -> ${dest}"
  if [ -d "${dest}/.git" ]; then
    git -C "${dest}" fetch --depth 1 origin "${THEME_REF}"
    git -C "${dest}" checkout -q FETCH_HEAD
  else
    rm -rf "${dest}"
    git clone --depth 1 --branch "${THEME_REF}" "${url}" "${dest}" \
      || git clone --depth 1 "${url}" "${dest}"
    if [ "${THEME_REF}" != "main" ] && [ "${THEME_REF}" != "master" ]; then
      git -C "${dest}" checkout -q "${THEME_REF}" || true
    fi
  fi
  echo "${dest}"
}

build_source_list() {
  if [ -n "${PROJECT_DOCU_PATHS:-}" ]; then
    printf '%s\n' "${PROJECT_DOCU_PATHS}" | tr ',;' '\n' | while IFS= read -r line || [ -n "${line}" ]; do
      line="$(echo "${line}" | xargs)"
      [ -z "${line}" ] && continue
      printf '%s\n' "${line}"
    done
    return 0
  fi
  printf '%s\n' "${THEME_PATH}"
  printf '%s\n' ".winccoa-docu-builder"
}

theme_abs="$(ensure_theme)"
mapfile -t sources < <(build_source_list)

echo "Preparing projectDocu merge sources:"
printf '  - %s\n' "${sources[@]}"

# shellcheck disable=SC2086
"${SCRIPT_DIR}/merge-project-docu.sh" "${sources[@]}"

# Marker so clean scripts / humans know these are generated.
{
  echo "# Generated by prepare-project-docu.sh - do not edit."
  echo "# Theme: ${THEME_REPOSITORY}@${THEME_REF}"
  echo "# Worker: ${WORKER_PATH}"
  date -u +"# UTC: %Y-%m-%dT%H:%M:%SZ"
} > "${REPO_ROOT}/${WORKER_PATH}/data/projectDocu/.generated-by-docu-builder"

echo "projectDocu prepare complete."
